language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository
before_install:
  - sudo apt-get install sshpass
before_script:
  - echo $GOOGLE_SERVICES | base64 --decode --ignore-garbage > app/google-services.json
script:
  - ./gradlew assembleDebug testDebugUnit lintDebug
  - ./gradlew assembleDebugAndroidTest
  - sshpass -e scp -o StrictHostKeyChecking=no app/build/outputs/apk/debug/app-debug.apk androidci@calebzor.redirectme.net:/home/androidci
  - sshpass -e scp -o StrictHostKeyChecking=no app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk androidci@calebzor.redirectme.net:/home/androidci
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb usb
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb shell input keyevent KEYCODE_WAKEUP
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb uninstall hu.tvarga.cheaplist
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb uninstall hu.tvarga.cheaplist.test
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb install -r app-debug.apk
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb install -r app-debug-androidTest.apk
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb shell am instrument -w -e emma true -e coverageFile "/sdcard/coverage.ec" hu.tvarga.cheaplist.test/android.support.test.runner.AndroidJUnitRunner
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb shell input keyevent KEYCODE_POWER
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb pull "/sdcard/coverage.ec"
  - sshpass -e scp -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net:/home/androidci/coverage.ec .
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net rm /home/androidci/coverage.ec
  - mkdir -p /home/travis/build/Calebzor/CheapList/app/build/outputs/code-coverage/connected/
  - cp /home/travis/build/Calebzor/CheapList/coverage.ec /home/travis/build/Calebzor/CheapList/app/build/outputs/code-coverage/connected/coverage.ec
  - git fetch --unshallow
  - ./gradlew jacocoMergedTestReport sendCoverageToCodacy sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=calebzor-github -Dsonar.login=$CHEAPLIST_CALEBZOR_GITHUB_SONAR_KEY