language: android
addons:
  sonarcloud:
    organization: "calebzor-github"
    token:
      secure: ${SONAR_KEY}
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
#  - platform-tools
  - build-tools-26.0.2
#  - android-21
  - android-26
  - extra-android-m2repository
#  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
before_script:
  - echo $GOOGLE_SERVICES | base64 --decode --ignore-garbage > app/google-services.json
script:
#  - ./gradlew build jacocoMergedTestReport
  - ./gradlew build jacocoTestReport lint sonarqube
#  - ./gradlew build jacocoTestReport assembleAndroidTest
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
#  - ./gradlew connectedCheck
#  - ./gradlew lint sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)