language: android
jdk: oraclejdk8
before_install:
  - sudo apt-get install jq
  - sudo apt-get install sshpass
script:
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb usb
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb shell input keyevent KEYCODE_WAKEUP
  - sshpass -e ssh -o StrictHostKeyChecking=no androidci@calebzor.redirectme.net adb reboot